#!/usr/bin/env bash
set -euo pipefail

# Installs native runtime libraries and model assets used by talkd.
# Default install location: ~/.talkd
# Override with: TALKD_HOME=/path/to/talkd scripts/install-runtime.sh

TALKD_HOME="${TALKD_HOME:-$HOME/.talkd}"
SHERPA_VERSION="${SHERPA_VERSION:-v1.13.3}"
ONNXRUNTIME_VERSION="${ONNXRUNTIME_VERSION:-1.24.4}"

STT_MODEL_NAME="sherpa-onnx-whisper-tiny.en"
STT_MODEL_URL="https://github.com/k2-fsa/sherpa-onnx/releases/download/asr-models/${STT_MODEL_NAME}.tar.bz2"

TTS_MODEL_NAME="kokoro-en-v0_19"
TTS_MODEL_URL="https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/${TTS_MODEL_NAME}.tar.bz2"

log() { printf '\033[1;34m[install]\033[0m %s\n' "$*"; }
err() { printf '\033[1;31m[error]\033[0m %s\n' "$*" >&2; }

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    err "Missing required command: $1"
    exit 1
  }
}

platform() {
  local os arch repo libdir ext
  os="$(uname -s)"
  arch="$(uname -m)"

  case "$os:$arch" in
    Darwin:arm64)
      repo="sherpa-onnx-go-macos"
      libdir="aarch64-apple-darwin"
      ext="dylib"
      ;;
    Darwin:x86_64)
      repo="sherpa-onnx-go-macos"
      libdir="x86_64-apple-darwin"
      ext="dylib"
      ;;
    Linux:x86_64)
      repo="sherpa-onnx-go-linux"
      libdir="x86_64-unknown-linux-gnu"
      ext="so"
      ;;
    Linux:aarch64|Linux:arm64)
      repo="sherpa-onnx-go-linux"
      libdir="aarch64-unknown-linux-gnu"
      ext="so"
      ;;
    *)
      err "Unsupported platform: $os $arch"
      exit 1
      ;;
  esac

  printf '%s\t%s\t%s\n' "$repo" "$libdir" "$ext"
}

download_file() {
  local url="$1"
  local out="$2"
  if [ -s "$out" ]; then
    log "Already exists: $out"
    return
  fi
  log "Downloading $(basename "$out")"
  curl -L --fail --retry 3 --retry-delay 2 -o "$out.tmp" "$url"
  mv "$out.tmp" "$out"
}

install_libs() {
  local repo="$1"
  local libdir="$2"
  local ext="$3"
  local base="https://raw.githubusercontent.com/k2-fsa/${repo}/${SHERPA_VERSION}/lib/${libdir}"

  mkdir -p "$TALKD_HOME/lib"

  if [ "$ext" = "dylib" ]; then
    download_file "$base/libsherpa-onnx-c-api.dylib" "$TALKD_HOME/lib/libsherpa-onnx-c-api.dylib"
    download_file "$base/libonnxruntime.${ONNXRUNTIME_VERSION}.dylib" "$TALKD_HOME/lib/libonnxruntime.${ONNXRUNTIME_VERSION}.dylib"
    ln -sf "libonnxruntime.${ONNXRUNTIME_VERSION}.dylib" "$TALKD_HOME/lib/libonnxruntime.dylib"
  else
    download_file "$base/libsherpa-onnx-c-api.so" "$TALKD_HOME/lib/libsherpa-onnx-c-api.so"
    download_file "$base/libonnxruntime.so.${ONNXRUNTIME_VERSION}" "$TALKD_HOME/lib/libonnxruntime.so.${ONNXRUNTIME_VERSION}"
    ln -sf "libonnxruntime.so.${ONNXRUNTIME_VERSION}" "$TALKD_HOME/lib/libonnxruntime.so"
  fi
}

install_tar_model() {
  local name="$1"
  local url="$2"
  local target_parent="$3"
  local target="$target_parent/$name"

  mkdir -p "$target_parent"
  if [ -d "$target" ]; then
    log "Already exists: $target"
    return
  fi

  local tmp
  tmp="$(mktemp -d)"

  log "Downloading model: $name"
  curl -L --fail --retry 3 --retry-delay 2 -o "$tmp/$name.tar.bz2" "$url"
  log "Extracting model: $name"
  tar xjf "$tmp/$name.tar.bz2" -C "$tmp"
  mv "$tmp/$name" "$target"
  rm -rf "$tmp"
}

write_env_file() {
  cat > "$TALKD_HOME/talkd.env" <<EOF
# Generated by scripts/install-runtime.sh
TALKD_HOME="$TALKD_HOME"
TALKD_LIB_DIR="$TALKD_HOME/lib"
TALKD_STT_MODEL_DIR="$TALKD_HOME/models/stt/$STT_MODEL_NAME"
TALKD_TTS_MODEL_DIR="$TALKD_HOME/models/tts/$TTS_MODEL_NAME"
EOF
}

main() {
  need_cmd uname
  need_cmd curl
  need_cmd tar
  need_cmd mktemp

  mkdir -p "$TALKD_HOME" "$TALKD_HOME/bin" "$TALKD_HOME/lib" "$TALKD_HOME/models/stt" "$TALKD_HOME/models/tts"

  IFS=$'\t' read -r repo libdir ext < <(platform)

  log "Installing to: $TALKD_HOME"
  log "Platform runtime: $repo / $libdir"

  install_libs "$repo" "$libdir" "$ext"
  install_tar_model "$STT_MODEL_NAME" "$STT_MODEL_URL" "$TALKD_HOME/models/stt"
  install_tar_model "$TTS_MODEL_NAME" "$TTS_MODEL_URL" "$TALKD_HOME/models/tts"
  write_env_file

  log "Done"
  printf '\nInstalled layout:\n'
  find "$TALKD_HOME" -maxdepth 3 -type d | sort
  printf '\nEnvironment file:\n  %s\n' "$TALKD_HOME/talkd.env"
  printf '\nNext service binary should be installed to:\n  %s/bin/talkd-service\n' "$TALKD_HOME"
  printf 'and should load libraries from:\n  %s/lib\n' "$TALKD_HOME"
}

main "$@"
